# Generated by Django 4.1 on 2022-09-21 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0003_reviewtoreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
