# Generated by Django 4.1 on 2022-09-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_report_review_report_reviewtoreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.products'),
        ),
    ]
