# Generated by Django 4.1 on 2022-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_report_reported_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='한 번만 신고',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_user', 'review'), name='한 번만 신고'),
        ),
    ]
