# Generated by Django 4.1 on 2022-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_remove_report_한 번만 신고_report_한 번만 신고'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
