# Generated by Django 4.1 on 2022-10-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_purchasehistory_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.products'),
        ),
        migrations.AlterField(
            model_name='reviewtoreview',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewtoreviews', to='shops.review'),
        ),
    ]
